### PR TITLE
Allow reCaptcha support

### PR DESCRIPTION
**Pull request by russellocean**
Download the reCaptcha extension here
https://addons.mozilla.org/firefox/downloads/file/3423472/recaptcha_solver-5.7-fx.xpi
place in your root directory of project and youre done

I hope I put this in the right place, I've never used python before.

### CODE REVIEW

**Comment by LonleyViper** [comment]
In the root directory of Firefox or the project? How does the project or mozilla know to run the addon?

**Comment by LonleyViper** [comment]
it seems like you have to buy a key for an API to use this addon. Seems fishy?

**Comment by LonleyViper** [comment]
Okay. Used the service. Confirmed it worked....by accidently ordering a fucking 2060 super lol.

Was unable to load the extension with the updated code automatically. Also is there a way way to load the API key in python?

**Comment by russellocean** [comment]
> Okay. Used the service. Confirmed it worked....by accidently ordering a fucking 2060 super lol.
> 
> Was unable to load the extension with the updated code automatically. Also is there a way way to load the API key in python?

Hey do you mind checking it out again, I made the extension add later in the cycle, from my testing it should be added every time now. There is a way to load the API key in python but this will require us to dynamically link with the captchas and send off the request. Much easier to just use someone else prebuilt extension.

**Comment by LonleyViper** [comment]
thx Russ! Will try to test it later! Not sure I can afford any more 2060's right now xD

**Comment by russellocean** [comment]
> thx Russ! Will try to test it later! Not sure I can afford any more 2060's right now xD

Oh no! I completely missed that, contact nvidia support they can cancel it in a few mins. Alot of people have accidently bought 2060's so you'll be good.

**Comment by russellocean** [comment]
Security concerns. Nevermind.

**Comment by LonleyViper** [comment]
Mind if I ask what was up?

**Comment by russellocean** [comment]
> Mind if I ask what was up?

Nothing malicious, people in discord were flagging because the extension is "sketchy looking" rather not be constantly pinged of it. I am still using it, and you can rename the recaptcha_solver-5.7-fx.xpi to recaptcha_solver-5.7-fx.zip to open up the extension and view the code. Easier to just close it than be bothered by people.

**Comment by LonleyViper** [comment]
ah i get ya! What discord is this I feel left out xD

**Comment by russellocean** [comment]
> ah i get ya! What discord is this I feel left out xD
Here you go - https://discord.gg/rjPXUw3

**Comment by LonleyViper** [comment]
Thx for the link dude. For what its worth, im using it and have tested- its going great :D

**Pull request closed without merging**
