### PR TITLE
Added useful exception if Mozilla can't be located

### PR DESCRIPTION
**Pull request by ericchansen**
This PR adds just two lines of codes to improve the user's experience if they don't have Mozilla Firefox installed on their local machine.

### CODE REVIEW

**Comment by krcm0209** [comment]
Looks good to me.

**Comment by philippnormann** [comment]
Hey  @ericchansen, nice usability improvement! Please make one minor adjustment: Change the Exception type from Exception to FileNotFoundError. As soon as you make that change, I will merge this PR :+1:

**Comment by ericchansen** [comment]
@philippnormann, that's a good suggestion. Thanks! It's updated now.

**Comment by philippnormann** [comment]
Looks good to me! Thanks for your contribution :slightly_smiling_face:

**Pull request merged**
